name: osm_nominatim
description: A library to perform OSM Nominatim searches also supporting reverse searches
version: 2.0.1
homepage: https://github.com/provokateurin/osm-nominatim

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ">=0.13.0 <0.14.0"
dev_dependencies:
  test: ^1.24.3
